pipeline {
    agent any

     tools {
            maven 'Maven-1'
        }

    environment {
        DOCKER_IMAGE = "sachincomviva/payment-service:${BUILD_NUMBER}"
    }

    stages {
        stage('Test') {
            steps {
                dir('Payment_Service') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Payment_Service') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Payment_Service') {
                    sh 'docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login \
                            -u "$DOCKER_USERNAME" \
                            --password-stdin

                        docker push ${DOCKER_IMAGE}
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "Build and Docker push completed successfully."
        }

        failure {
            echo "Pipeline failed."
        }
    }
}