# Application
spring.application.name=payment-service
server.port=5010
server.servlet.context-path=/payment-service

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mpos
spring.datasource.username=mpos
spring.datasource.password=mpos
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Kafka Producer Properties
spring.kafka.bootstrap-servers=kafka-kafka-bootstrap.kafka.svc:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer